### ISSUE TITLE
KeyError: 'tracks'

### ISSUE THREAD

**Issue by rarealphacat** [jaris58/joox_dl#13]
Error running the below cmd:
python joox_dl.py -hq -m -u https://www.joox.com/hk/album/zqqPGaE4OdJH95D5ZlisMw==

Traceback (most recent call last):
  File "/home/xxxxx/Downloads/joox_dl/joox_dl.py", line 518, in <module>
    main()
  File "/home/xxxxx/Downloads/joox_dl/joox_dl.py", line 443, in main
    total_song = data['tracks']['total_count']
KeyError: 'tracks'

**Comment by jaris58** [comment]
![image](https://user-images.githubusercontent.com/34656650/147574228-685eb4e0-f4d5-4f16-bf12-b9f436a69976.png)
as you can see i have problem with my connection, i need free vpn with hongkong location, can you suggest me what I can use?

**Comment by rarealphacat** [comment]
Try proton VPN

**Comment by jaris58** [comment]
can u provide free vpn hongkong? proton VPN is paid vpn

**Comment by rarealphacat** [comment]
try windscribe.com
